{% set name = "xrft" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xgcm/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 51705777f078830da7b4f6b72447f4e52179caaa05cc3e51fd6be6851cfc885e
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - pytest-runner
  run:
    - python >=3.6
    - dask
    - docrep
    - future
    - numpy
    - scipy
    - xarray

test:
  imports:
    - xrft
    - xrft.tests

about:
  home: https://github.com/xgcm/xrft
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fourier transforms for xarray data
  dev_url: https://github.com/xgcm/xrft

extra:
  recipe-maintainers:
    - kynan
    - rabernat
    - roxyboy
