{% set name = "xrft" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xgcm/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ccb1deee04729f9d6e0b4bb7ba2227f85844112e6ca2cfde9c41a13ad129cd8b
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - pytest-runner
  run:
    - python >=3.6
    - dask
    - docrep
    - future
    - numpy
    - scipy
    - xarray

test:
  imports:
    - xrft
    - xrft.tests

about:
  home: https://github.com/xgcm/xrft
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fourier transforms for xarray data
  dev_url: https://github.com/xgcm/xrft

extra:
  recipe-maintainers:
    - kynan
    - rabernat
    - roxyboy
