{% set name = "xrft" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xgcm/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4278ab7da8e17570201ef1b952ac5e7ed0cc732487862ba792f4714dd41b3fa6
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-runner
  run:
    - python
    - dask
    - docrep
    - future
    - numpy
    - scipy
    - xarray

test:
  imports:
    - xrft
    - xrft.tests

about:
  home: https://github.com/xgcm/xrft
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fourier transforms for xarray data
  dev_url: https://github.com/xgcm/xrft

extra:
  recipe-maintainers:
    - kynan
    - rabernat
    - roxyboy
